# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lemonade and Information
tagline:             'The personal website of Joshua Beatty'
description:         'Libraries, history, &c.'
url:                 http://jfbeatty.github.io
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Joshua Beatty
  twitter:           https://twitter.com/beattyjf
  zotero:            https://www.zotero.org/jfbeatty
  pinboard:          https://pinboard.in/u:jfbeatty
  github:            https://github.com/jfbeatty
  email:             jfbeatty@gmail.com

# Prose.io
prose:
  media:             "images"
  metadata:
  	_posts:
  		- name: "date"
  		  field:
  		  	element: "text"
  		  	value: CURRENT_DATETIME

# Custom vars
version:             1.0.0
